[colors]
background = '#282a36'
foreground = '#eff0eb'
selection-background = '#92bcd0'
selection-foreground = '#000000'
cursor = '#eaeaea'
black = '#000000'
red = '#ff5c57'
green = '#94e362'
yellow = '#eebd70'
blue = '#99ecfe'
magenta = '#ff6ac1'
cyan = '#5fdeed'
white = '#f1f1f0'
light_black = '#686868'
light_red = '#ff5c57'
light_green = '#94e362'
light_yellow = '#efc781'
light_blue = '#99ecfe'
light_magenta = '#ff6ac1'
light_cyan = '#87e0f0'
light_white = '#f1f1f0'
