# Dogxi Misty
[colors]
foreground = "#eff0eb"
background = "#282a36"
cursor_bg = "#eaeaea"
cursor_border = "#eaeaea"
cursor_fg = "#282a36"
selection_bg = "#92bcd0"
selection_fg = "#000000"

ansi = ["#000000","#ff5c57","#94e362","#eebd70","#99ecfe","#ff6ac1","#5fdeed","#f1f1f0"]
brights = ["#686868","#ff5c57","#94e362","#efc781","#99ecfe","#ff6ac1","#87e0f0","#f1f1f0"]
