tags = ["dark"]

[theme.colors]
background = "#282a36"
foreground = "#eff0eb"
bright-foreground = "#f8f8f8"

[theme.colors.palette]
0 = "#000000"
1 = "#ff5c57"
2 = "#94e362"
3 = "#eebd70"
4 = "#99ecfe"
5 = "#ff6ac1"
6 = "#5fdeed"
7 = "#f1f1f0"
8 = "#686868"
9 = "#ff5c57"
10 = "#94e362"
11 = "#efc781"
12 = "#99ecfe"
13 = "#ff6ac1"
14 = "#87e0f0"
15 = "#f1f1f0"
